version: "3.1"

services:

  # Master
  spark-master:
    image: bitnami/spark:latest
    container_name: spark-master
    environment:
      - SPARK_MODE=master
    ports:
      - "8080:8080"
      - "7077:7077"
    networks:
      - spark-network

  # Worker
  spark-worker:
    image: bitnami/spark:latest
    container_name: spark-worker
    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER_URL=spark://spark-master:7077
    depends_on:
      - spark-master
    networks:
      - spark-network

  # Jupyter
  jupyter:
    image: jupyter/pyspark-notebook
    container_name: jupyter
    ports:
      - "8888:8888"
    volumes:
      - ./notebooks:/home/jovyan/work
    networks:
      - spark-network
    depends_on:
      - spark-master
      - spark-worker
    command: start-notebook.sh --NotebookApp.token=''

  # Elasticsearch
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.10.2
    container_name: elasticsearch
    environment:
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - "discovery.type=single-node"
      - xpack.security.enabled=false
    ports:
      - "9200:9200"
    volumes:
      - elasticsearch_data:/usr/share/elasticsearch/data
    networks:
      - spark-network

  # Kibana
  kibana:
    image: docker.elastic.co/kibana/kibana:8.10.2
    container_name: kibana
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
    ports:
      - "5601:5601"
    networks:
      - spark-network
    depends_on:
      - elasticsearch

  # Hadoop NameNode
  namenode:
    image: bde2020/hadoop-namenode:2.0.0-hadoop3.2.1-java8
    container_name: namenode
    environment:
      - CLUSTER_NAME=mycluster
    ports:
      - "50070:50070"  # Web UI
      - "8020:8020"   # HDFS Namenode RPC
    volumes:
      - namenode-data:/hadoop/dfs/name
    networks:
      - spark-network
    command: /bin/bash -c "hdfs namenode -format && hdfs --daemon start namenode && tail -f /dev/null"

  # Hadoop DataNode
  datanode:
    image: bde2020/hadoop-datanode:2.0.0-hadoop3.2.1-java8
    container_name: datanode
    environment:
      - CLUSTER_NAME=mycluster
      - NAMENODE_ADDRESS=namenode:8020
    depends_on:
      - namenode
    ports:
      - "50075:50075"  # Web UI
    volumes:
      - datanode-data:/hadoop/dfs/data
    networks:
      - spark-network
    command: /bin/bash -c "hdfs --daemon start datanode && tail -f /dev/null"

networks:
  spark-network:
    driver: bridge

volumes:
  elasticsearch_data:
    driver: local
  namenode-data:
    driver: local
  datanode-data:
    driver: local
